repos:
  - repo: https://github.com/backplane/pre-commit-rust-hooks
    rev: v1.1.0
    hooks:
      - id: fmt
      - id: check
      - id: clippy

  - repo: https://github.com/est31/cargo-udeps
    rev: v0.1.47
    hooks:
      - id: udeps