repos:
  - repo: https://github.com/backplane/pre-commit-rust-hooks
    rev: v1.1.0
    hooks:
      - id: fmt
      - id: check
      - id: clippy
        args: ["--all-targets", "--workspace"]

  - repo: https://github.com/est31/cargo-udeps
    rev: v0.1.47
    hooks:
      - id: udeps

  - repo: local
    hooks:
      - id: audit
        name: audit
        description: Checks to find vulnerable or unmaintained versions
        entry: cargo audit
        language: system
        pass_filenames: false
