[package]
name = "aaru"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scc = "2.1.1"
geo = "0.28.0"

# Algorithm
rstar = { version = "0.12.0", features = ["serde"] }
petgraph = { version = "0.6.5", features = ["serde-1", "graphmap", "rayon"] }

# Testing Deps.
osmpbfreader = "0.16.1"
serde = { version = "1.0.200", features = ["derive"] }
bincode = "1.3.3"

# Logging Utility
log = "0.4.20"
env_logger = "0.10.0"
test-log = { version = "0.2.16", features = ["log"] }

# gRPC Server Dependencies
tonic = { version = "0.11.0", features = ["tls", "tls-roots"] }
tonic-reflection = { version = "0.11.0" }
prost = { version = "0.12.6" }
tokio = { version = "1.37.0", features = ["rt", "rt-multi-thread", "macros"] }

# Tracing
tracing = { version = "0.1.16", optional = true }
tracing-subscriber = { version = "0.3", features = ["tracing-log", "fmt", "env-filter"], optional = true }
opentelemetry = "0.23.0"
opentelemetry_sdk = { version = "0.23.0", features = ["rt-tokio"] }
tracing-opentelemetry = "0.24.0"
opentelemetry-otlp = { version = "0.16.0", features = ["tls"] }

# Optimisations and Compression
rayon = "1.10.0"
memmap2 = { version = "0.9.4", optional = true }
flate2 = { version = "1.0.30", features = ["zlib-ng"] }
either = "1.11.0"
dotenv = "0.15.0"

[build-dependencies]
tonic-build = { version = "0.11.0", features = ["prost"] }
prost-build = { version = "0.12.6"}

[dev-dependencies]
osmpbf = { version = "0.3.3", features = ["zlib-ng"], default-features = false }

[features]
default = ["mmap", "tracing"]
mmap = ["memmap2"]
tracing = ["dep:tracing", "tracing-subscriber"]

[profile.release]
opt-level = 3
lto = true
