[package]
name = "aaru"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "route"
path = "src/bin/route.rs"

[[bin]]
name = "tile"
path = "src/bin/tile.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scc = "2.1.1"
geo = "0.28.0"

# Algorithm
rstar = { version = "0.12.0", features = ["serde"] }
petgraph = { version = "0.6.5", features = ["serde-1", "graphmap", "rayon"] }

# Testing Deps.
osmpbfreader = "0.16.1"
serde = { version = "1.0.200", features = ["derive"] }
bincode = "1.3.3"

# Logging Utility
log = "0.4.20"
env_logger = "0.10.0"
test-log = { version = "0.2.16", features = ["log"] }

# gRPC Server Dependencies
tonic = { version = "0.11.0", features = ["tls", "tls-roots"] }
tonic-reflection = { version = "0.11.0" }
prost = { version = "0.12.6" }
tokio = { version = "1.38.0", features = ["rt", "rt-multi-thread", "macros"] }

# Tracing
tracing = { version = "0.1.16", optional = true }
tracing-subscriber = { version = "0.3", features = ["tracing-log", "fmt", "env-filter"], optional = true }
opentelemetry = { version = "0.23.0", optional = true }
opentelemetry_sdk = { version = "0.23.0", features = ["rt-tokio"], optional = true }
tracing-opentelemetry = {  version = "0.24.0", optional = true }
opentelemetry-otlp = { version = "0.16.0", features = ["tls"], optional = true }

# Optimisations and Compression
rayon = "1.10.0"
memmap2 = { version = "0.9.4", optional = true }
flate2 = { version = "1.0.30", features = ["zlib-ng"] }
either = "1.11.0"
dotenv = "0.15.0"
bigtable_rs = { version = "0.2.10" }
chrono = "0.4.38"
fast_hilbert = "2.0.0"

tower-http = { version = "0.5.2", features = ["cors"] }
axum = { version = "0.7.5", features = ["query"] }
axum-macros = "0.4.1"
serde_qs = "0.13.0"

[build-dependencies]
tonic-build = { version = "0.11.0", features = ["prost"] }
prost-build = { version = "0.12.6"}

[dev-dependencies]
osmpbf = { version = "0.3.3", features = ["zlib-ng"], default-features = false }

[features]
default = ["mmap", "tracing"]
mmap = ["memmap2"]
tracing = ["dep:tracing", "tracing-subscriber", "opentelemetry", "opentelemetry_sdk", "tracing-opentelemetry", "opentelemetry-otlp"]

[profile.release]
opt-level = 3
lto = true
