[package]
name = "aaru"
version = "0.1.8"
edition = "2021"
readme = "readme.md"
description = "Actionable Area Routing Utilities for OSM and MVT"
license = "MIT"
include = ["docs", "src/**/*", "proto/**/*", "build.rs", "readme.md"]

[lib]
name = "aaru"
path = "src/lib.rs"

[[example]]
name = "route"
required-features = ["route", "grpc_server"]
path = "examples/route.rs"

[[example]]
name = "tile"
required-features = ["tile"]
path = "examples/tile.rs"

[dependencies]
# Algorithm
rstar = { version = "0.12.0", features = ["serde"] }
petgraph = { version = "0.6.5", features = ["serde-1", "graphmap", "rayon"] }

# Testing Deps.
serde = { version = "1.0.200", features = ["derive"] }

# Logging Utility
log = { version = "0.4.20", features = [] }
env_logger = "0.11.5"
test-log = { version = "0.2.16", features = ["log"] }

# gRPC Server Dependencies [Optional-"grpc_server"]
tonic = { version = "0.12.1", features = ["tls", "tls-roots"], optional = true }
tonic-reflection = { version = "0.12.1", optional = true }
bytes = { version = "1.7.1", features = ["default"] } # Required for io::Cursor
prost = { version = "0.13.1"}
tokio = { version = "1.38.0", features = ["rt", "rt-multi-thread", "macros"], optional = true }

# HTTP Server Dependencies [Optional-"http_server"]
tower-http = { version = "0.5.2", features = ["cors"], optional = true }
axum = { version = "0.7.5", features = ["query"], optional = true }
axum-macros = { version = "0.4.1", optional = true }
serde_qs = { version = "0.13.0", optional = true }

# Tracing [Optional-"tracing"]
tracing = { version = "0.1.16", optional = true }
tracing-subscriber = { version = "0.3", features = ["tracing-log", "fmt", "env-filter"], optional = true }
opentelemetry = { version = "0.24.0", optional = true }
opentelemetry_sdk = { version = "0.24.1", features = ["rt-tokio"], optional = true }
tracing-opentelemetry = {  version = "0.25.0", optional = true }
opentelemetry-otlp = { version = "0.17.0", features = ["tls"], optional = true }

# Optimisations and Compression
rayon = "1.10.0"
either = "1.11.0"
dotenv = "0.15.0"
chrono = "0.4.38"
flate2 = { version = "1.0.30", features = ["zlib-ng"], optional = true }
memmap2 = { version = "0.9.4", optional = true }
fast_hilbert = {  version = "2.0.0", optional = true }
scc = { version = "2.1.1", optional = true }
geo = "0.28.0"
wkt = "0.11.0"
bytemuck = "1.17.0"

[build-dependencies]
tonic-build = { version = "0.12.1", features = ["prost"] }
prost-build = { version = "0.13.1"}

[dev-dependencies]
osmpbf = { version = "0.3.3", features = ["zlib-ng"], default-features = false }
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "codec_sweep"
harness = false

[[bench]]
name = "codec_target"
harness = false

[features]
default = ["codec", "mmap"]
mmap = ["memmap2"]

tracing = ["dep:tracing", "tracing-subscriber", "opentelemetry", "opentelemetry_sdk", "tracing-opentelemetry", "opentelemetry-otlp"]

grpc_server = ["tracing", "tonic", "tonic-reflection", "tokio"]
http_server = ["tower-http", "axum", "axum-macros", "serde_qs", "tokio"]

tile = ["http_server", "fast_hilbert"]
route = ["scc", "codec"]
codec = ["flate2"]

[package.metadata.docs.rs]
features = ["tile", "route", "codec"]

[profile.release]
opt-level = 3
lto = true

[profile.bench]
opt-level = 3
lto = true