[package]
name = "aaru"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
osmpbf = { version = "0.3.3", features = ["zlib-ng"], default-features = false }
scc = "2.1.1"
geo = "0.28.0"
rstar = { version = "0.12.0", features = ["serde"] }
petgraph = { version = "0.6.4", features = ["serde-1"] }

# Testing Deps.
osmpbfreader = "0.16.1"
serde = { version = "1.0.200", features = ["derive"] }
bincode = "1.3.3"
