name: Benchmark

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

env:
  PROTOC_VERSION: 3.20.3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: install protoc
        uses: taiki-e/install-action@v2
        with:
          tool: protoc@${{ env.PROTOC_VERSION }}

      - name: Rust Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: 🔨 Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: bench
        run: cargo +nightly bench -- --output-format bencher | tee output.txt

      - name: Download previous benchmark data
        uses: actions/cache@v1
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'cargo'
          output-file-path: output.txt
          external-data-json-path: ./cache/benchmark-data.json
          fail-on-alert: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-on-alert: true
          comment-always: true
          summary-always: true
          alert-comment-cc-users: '@bennjii'

      - uses: actions/upload-artifact@v1
        with:
          name: rsstable_${{ github.sha }}_bench
          path: ./target/criterion