name: Test

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

env:
  PROTOC_VERSION: 3.20.3
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: install protoc
        uses: taiki-e/install-action@v2
        with:
          tool: protoc@${{ env.PROTOC_VERSION }}

      - name: Rust Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - name: 🧪 Test
        uses: actions-rs/cargo@v1
        with:
          command: nextest
          args: run --profile ci

